version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:14.7-alpine
    restart: always
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisDB:/data
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=root
    ports:
      - 8081:8081
    depends_on:
      - redis
volumes:
  redisDB:
  postgres-data: